### PR TITLE
Fix for Issue #8

### PR DESCRIPTION
**Pull request by Twinkletoes**

### CODE REVIEW

**Comment by BryanHunt** [comment]
I just discovered a problem with this fix.  The vertical and horizontal composite examples to not initialize correctly.  The width of the space for the sash is too wide for the child split until you drag the sash in the parent view, then the child split redraws correctly.  I'm going to revert this for now.

**Comment by Twinkletoes** [comment]
Ok, I'll test with composites and resubmit

**Comment by BryanHunt** [comment]
In case you didn't happen to notice, there is a test app bundled with the addon that has the various composites already set up.

**Comment by Twinkletoes** [comment]
:) I hadn't noticed.  Testing now

**Pull request merged**
