### PR TITLE
Split by pixels not percent

### LINKED ISSUE #14: Resizing window so that split conflicts with min-width makes sash overlap child view

### PR DESCRIPTION
**Pull request by BryanCrotaz**
Fixes #14, #25, #27
Major rewrite to better handle resizing the outer view. Internally everything is now in pixels, not %.
Delegated `minSize` down to the child view which makes handling nested views much easier.
Renamed `movable*` to `anchor*` and removed `fixed*` which wasn't used, making the code more readable.
Used `ember-resize` to detect changes to outer view. Note that default environment settings don't enable height change notification

### CODE REVIEW

**Comment by BryanCrotaz** [comment]
Seems to fix all the problems we were seeing in our ember app

**Comment by BryanHunt** [comment]
I'll try to get this integrated tonight.  Looks like the unit tests are broken.

**Comment by BryanCrotaz** [comment]
Looks like a timeout rather than a break. The change I just pushed shouldn't make it break

**Comment by BryanHunt** [comment]
Ok, I'll have a look later.

**Comment by BryanCrotaz** [comment]
Not totally happy using ember-resize as it monitors the browser window rather than the containing div. Looking at using browser events instead, but will submit as a new PR if I make it work

**Comment by BryanHunt** [comment]
I pulled these changed into a local branch and I'm getting runtime errors.  Did you leave your branch in a clean state?  Here's how I pulled the code:

```
git checkout -b BryanCrotaz-split_by_pixels_not_percent master
git pull https://github.com/BryanCrotaz/ember-split-view.git split_by_pixels_not_percent
```
dummy_and_dummy

**Comment by BryanCrotaz** [comment]
Odd... no dirty files here. Will check thoroughly

**Comment by BryanCrotaz** [comment]
What's your global ember version?

**Comment by BryanCrotaz** [comment]
Upgrade of ember-cli hadn't been done correctly.

One outstanding problem - `addon/styles/split-view.css` is not being compiled into `vendor.css`, but can't see why not. Any ideas?

**Comment by BryanCrotaz** [comment]
See https://github.com/ember-cli/ember-cli/issues/4615

**Comment by BryanHunt** [comment]
My global ember-cli is 1.13.6.  ember-cli for ember-split-view is still 0.2.7.  Should we update it to the latest ember-cli?

**Comment by BryanCrotaz** [comment]
My branch is updated to 1.13.7
It's not currently bringing the stylesheet in but everything else works and a ton of deprecations are gone.

**Comment by BryanHunt** [comment]
Hmmm, how is your branch updated?  package.json still lists ember-cli at 0.2.7.  I see that the pull I did picked up package.json.  Confused.

**Comment by BryanCrotaz** [comment]
It's in my latest commit
https://github.com/BryanCrotaz/ember-split-view/commit/3c46b782e8adfda47df12122299e2a9f214a2f83

**Comment by BryanHunt** [comment]
Ok, I just did another pull, and I see the changes.  I'll give it a try later today.

**Comment by BryanCrotaz** [comment]
You'll find the layouts are all broken - in chrome, paste the content of `/addon/styles/split-view.css` onto the end of `vendor.css` and it will all start to work

**Comment by BryanCrotaz** [comment]
Fixed it. Had to put the css file in vendor and import it in index.js

**Comment by BryanCrotaz** [comment]
Passes on ember release, fails on beta!

**Comment by BryanCrotaz** [comment]
Others seem to be getting fails on beta and canary so I'd say merge this and we'll fix again for ember 2.0.0 when there's clear testing story

https://github.com/ember-cli/ember-cli/issues/4633

**Comment by BryanHunt** [comment]
I picked up your latest changes and it seems to be working except for min with and height.  It allows me to drag the sash past the min.

**Comment by BryanCrotaz** [comment]
@stefanpenner says the beta test failure problem is in `ember-data` so I reckon these changes can be merged safely.

**Comment by BryanCrotaz** [comment]
I had a discussion about security at Ember London, and we agreed that addons should not require `'unsafe-inline'` CSP as this opens up security holes in the containing app.

I've refactored to remove the need for `'unsafe-inline'` in `ember-split-view`

**Comment by BryanHunt** [comment]
A most excellent contribution.  Thanks!

**Comment by BryanCrotaz** [comment]
:)

**Pull request merged**
