### PR TITLE
Fix layout when parent is position:absolute

### PR DESCRIPTION
**Pull request by Twinkletoes**
Moved more styling into css so app developer can override. Only dragged position is now inline.

Added css classes:

split-view, child, sash (self explanatory)
vertical, horizontal - classes on view,child and sash which say whether this level's sash is vertical or horizontal
nested - class on a child if it contains a nested split-view (css hides the scroll bars in this case)
dragging - class on view, child and sash when sash is being dragged, so app developer can decorate them

### CODE REVIEW

**Comment by Twinkletoes** [comment]
This PR has only one bug - when nested views are less wide than both the min-widths of the children the child views overlap (issue #14)

**Comment by BryanHunt** [comment]
This PR doesn't seem to play well with the demo app.  The sash appears to be on the order of 100 px wide, and the composites have an extra border.

**Comment by Twinkletoes** [comment]
Have you pulled my demo app changes?

**Comment by BryanHunt** [comment]
I picked up this PR.  Where are the changes to the demo app?

**Comment by Twinkletoes** [comment]
There's a pr on the demo app.

Sorry, new to GitHub. Tell me if I'm not doing this the right way.

**Comment by BryanHunt** [comment]
Ah, I'm using the demo app in this repo.  Could you submit the changes to this demo app.  That other demo app needs to go away.

**Pull request merged**
