### PR TITLE
Updated and adjusted this addons for run Ember.2.9

### PR DESCRIPTION
**Pull request by aureliosaraiva**
This Pull Request adjust a addons for run in Ember 2.9.

@BryanHunt parentView is private API:

**parentView** was removed
http://emberjs.com/api/classes/Ember.Component.html#property_parentView

Resolved bugfix for firefox:
`parseInt` would return **NaN**.
https://github.com/BryanHunt/ember-split-view/pull/38/files#diff-00b5994f58459f79a2d642e5196b05ebR131

README updated also!

### CODE REVIEW

**Comment by BryanHunt** [comment]
Does this PR supersede PR #37?

**Comment by aureliosaraiva** [comment]
@BryanHunt yes, tks

**Comment by aureliosaraiva** [comment]
@BryanHunt ?

**Comment by BryanHunt** [comment]
The build is failing on ember-beta.  Do we care about that?

**Comment by aureliosaraiva** [comment]
I would not worry about ember-beta right now.

The version that is in the master today does not work correctly in the current stable version.

After updating this PR, I have others to improve the addons as we are using in production in the company "Resultados Digitais".

I can send other PR when ember version 2.11 stable.

**Pull request merged**
